# Generated by Django 5.1.6 on 2025-03-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brands',
            field=models.ManyToManyField(blank=True, to='myapp.brand'),
        ),
    ]
