# Generated by Django 5.1.6 on 2025-03-12 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_address_alter_delivery_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.deliveryservice'),
        ),
    ]
