# Generated by Django 5.1.6 on 2025-03-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_deliveryservice_alter_delivery_delivery_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='requested', max_length=50),
        ),
        migrations.AddField(
            model_name='refund',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
